Add a test for integration/utils.py and small changes for tensorflow support
FHof/torchquad pull request #10
Opened 2021-11-08 10:20 UTC by FHof

This requires #5 (set_precision backend parameter) to be merged, and a change in environment.yml for backend installations.

2021-11-10 07:49 UTC, gomezzz requested changes
Some minor comments, also some design questions :)

2021-11-10 07:49 UTC, gomezzz commented on environment.yml
> +  - jax[cuda]>=0.2.22
From what I am reading there is no GPU version on conda / conda-forge. I presume this is the reason? (maybe add a comment here :) )

2021-11-10 07:49 UTC, gomezzz commented on environment.yml
> +  - tensorflow>=2.6.0
For TF there is definitely a conda version though, why not use that? (avoids nasty conflicts in my experience)

2021-11-10 07:49 UTC, gomezzz commented on environment.yml
> +- pip:
In general, I am not sure if it's a great idea to always install all frameworks we want to support. Do you have a smart idea for this? Or, if there is no better way we should at least mention that it will install all of them but that you can comment them out in the contributing sections in the [README](https://github.com/FHof/torchquad#contributing) and [docs](https://github.com/FHof/torchquad/blob/develop/docs/source/contributing.rst).

2021-11-10 07:49 UTC, gomezzz commented on environment.yml
> +- pip
Maybe, it might be worth setting the numpy version as well? (because depending the framework version this might cause complications?)

2021-11-10 07:49 UTC, gomezzz commented on torchquad/tests/utils_integration_test.py
> +            precision_supported_backends = ["numpy", "torch", "jax"]
Looking at this I am starting to realize that we will need a way to keep track which operations / parts  are supported by which framework. Maybe we should add it to all function docstrings. What do you think?

2021-11-10 07:49 UTC, gomezzz commented on torchquad/tests/utils_integration_test.py
> +            # FIXME: for some reason tensorflow is out of memory if the GPU
Could you create issues for these problems? We don't need to solve all of them short-term but it's probably better to have it centrally instead of in the code. When we merge into the original repo we can migrate outstanding issues.

2021-11-10 07:49 UTC, gomezzz commented on torchquad/tests/utils_integration_test.py
> +            # FIXME: for some reason tensorflow is out of memory if the GPU
Alternatively, we can create an issue in this repo to create issues for all FIXME entries once we merge into the main repo if you prefer that?

2021-11-10 07:49 UTC, gomezzz commented on torchquad/tests/utils_integration_test.py
> +def run_linspace_with_grads_tests(dtype_name, backend, requires_grad):
```suggestion
def _run_linspace_with_grads_tests(dtype_name, backend, requires_grad):
```

2021-11-10 07:49 UTC, gomezzz commented on torchquad/tests/utils_integration_test.py
> +            run_linspace_with_grads_tests(dtype_name, backend, requires_grad)
```suggestion
            _run_linspace_with_grads_tests(dtype_name, backend, requires_grad)
```

2021-11-10 07:49 UTC, gomezzz commented on torchquad/tests/utils_integration_test.py
> +def run_setup_integration_domain_tests(dtype_name, backend):
```suggestion
def _run_setup_integration_domain_tests(dtype_name, backend):
```

2021-11-10 07:49 UTC, gomezzz commented on torchquad/tests/utils_integration_test.py
> +            run_setup_integration_domain_tests(dtype_name, backend)
```suggestion
            _run_setup_integration_domain_tests(dtype_name, backend)
```

2021-11-10 07:49 UTC, gomezzz commented on torchquad/tests/utils_integration_test.py
> +def run_RNG_tests(dtype_name, backend):
```suggestion
def _run_RNG_tests(dtype_name, backend):
```

2021-11-10 07:49 UTC, gomezzz commented on torchquad/tests/utils_integration_test.py
> +            run_RNG_tests(dtype_name, backend)
```suggestion
            _run_RNG_tests(dtype_name, backend)
```

2021-11-10 07:49 UTC, gomezzz commented on torchquad/tests/utils_integration_test.py
> +        _RNG(backend, None).uniform(size=[3, 9]),
```suggestion
        _RNG(backend, 42).uniform(size=[3, 9]),
```

Using another fixed seed should make this more deterministic and collision less likely, I think?

2021-11-10 07:49 UTC, gomezzz commented on torchquad/tests/utils_integration_test.py
> +        _RNG(backend).uniform(size=[3, 9]),
```suggestion
        _RNG(backend,42*42).uniform(size=[3, 9]),
```

2021-11-10 07:49 UTC, gomezzz commented on torchquad/tests/utils_integration_test.py
> +        _RNG(backend).uniform(size=[3, 9]),
(This doesn't necessarily make sense if all are fixed though, 3 should then suffice, probably?)

2021-11-10 10:36 UTC, FHof commented on environment.yml
> +  - tensorflow>=2.6.0
I tried `tensorflow` and `tensorflow-gpu` from conda-forge and both were not compiled for the GPU, i.e. `is_built_with_cuda` returned false.
```sh
python3 -c 'import tensorflow as tf; print(tf.test.is_built_with_cuda(), tf.config.list_physical_devices("GPU"))'
```
Is there another tensorflow version for conda which is built with CUDA?

2021-11-10 10:47 UTC, FHof commented on torchquad/tests/utils_integration_test.py
> +        _RNG(backend, None).uniform(size=[3, 9]),
I intentionally omitted the seed directly after using a fixed seed two times to test if the RNG is randomly seeded when seed is omitted. I think I should mention this in the docstring or comments.

2021-11-11 10:43 UTC, FHof commented
> In general, I am not sure if it's a great idea to always install all frameworks we want to support. Do you have a smart idea for this? Or, if there is no better way we should at least mention that it will install all of them but that you can comment them out in the contributing sections in the README and docs.

To run the tests successfully, all backends need to be installed, and there may be users who want to install the CPU-only versions instead of CUDA versions, so I don't have a better idea than mentioning it in the README.

2021-11-11 11:32 UTC, FHof commented on environment.yml
> +  - tensorflow>=2.6.0
It works if I write cuda and a star in the build version.

2021-11-12 08:45 UTC, gomezzz approved these changes

2021-11-12 11:18 UTC, merged