Use the TORCHQUAD_LOG_LEVEL environment variable for the default log level if it exists
FHof/torchquad pull request #11
Opened 2021-11-08 10:26 UTC by FHof

A small one-line change so that the default log level can be changed with an environment variable

2021-11-10 06:59 UTC, gomezzz approved these changes
👍

2021-11-10 07:02 UTC, gomezzz requested changes
Ah, actually  just one small request. We should document this in the docs. Can you add one line mentioning it to

https://github.com/FHof/torchquad/blob/develop/docs/source/tutorial.rst in the minimal workign example

and in https://github.com/FHof/torchquad/blob/develop/README.md under usage?

2021-11-10 10:26 UTC, FHof commented
`tutorial.rst` and `README.md` now mention `TORCHQUAD_LOG_LEVEL`. I also added it to the `set_log_level` documentation.

2021-11-12 08:46 UTC, gomezzz approved these changes

2021-11-12 10:55 UTC, merged