Extend the existing tests for other backends than torch
FHof/torchquad pull request #12
Opened 2021-11-08 10:49 UTC by FHof

The first commit changes the test functions code and example function initialisations so that they work with other numerical backends (via autoray). 
The other commits change the tests of the respective integration rules so that they use other backends than only torch.

This requires the backend argument in set_precision (#5) and a change in environment.yml.

2021-11-18 13:25 UTC, gomezzz requested changes
Some minor comments, overall looking good!

2021-11-18 13:25 UTC, gomezzz commented on torchquad/tests/integration_test_utils.py
> +def compute_test_errors(
I don't think this function is ever used, is it?

2021-11-18 13:25 UTC, gomezzz commented on torchquad/tests/boole_test.py
> +def test_integrate_numpy():
Why not tensorflow?

2021-11-18 13:25 UTC, gomezzz commented on torchquad/tests/boole_test.py
> +def test_integrate_numpy():
Ah, sry just read it below.

2021-11-18 13:25 UTC, gomezzz commented on torchquad/tests/boole_test.py
> +def test_integrate_jax():
It may be cleaner to have something like

```Python
backends = ["numpy","torch","jax"]
set_log_level("INFO")
for backend in backends:
     set_precision("double", backend=backend)
     _run_boole_tests(backend)
```

?

Don't worry about the enable_cuda since we decided yesterday to have it default on, right?

Also, potentially, you could maybe determine `backends` depending on the installed ones (I think you can check codebased if a module is installed iirc) and only test those? (maybe throw a warning for nontested ones)

2021-11-18 13:25 UTC, gomezzz commented on torchquad/tests/integration_test_functions.py
> +            if is_complex:
Maybe stupid question, which of the backends actually support complex numbers? I know of np, torch but TF and jax do as well then?

2021-11-18 13:25 UTC, gomezzz commented on torchquad/tests/integration_test_functions.py
> +            # Tensorflow's exponentiation gives float64 values if x are float32
This is a little ugly. Is this related to the global precision problem? We might want to start writing down changes that we want to make when that problem is resolved

2021-11-18 13:25 UTC, gomezzz commented on torchquad/tests/monte_carlo_test.py
> +np_config.enable_numpy_behavior()
What is this for? Maybe add a comment explaining the line :)

2021-11-18 13:25 UTC, gomezzz commented on torchquad/tests/monte_carlo_test.py
> +    errors, funcs = run_example_functions(
Personally, I think a better name for the function may be something like `compute_integration_test_error` because it is a little unclear what the example functions are and what running them actually does?

2021-11-18 13:25 UTC, gomezzz commented on torchquad/tests/vegas_test.py
> +from integration_test_utils import compute_test_errors
Ah! Here it is used! I see. Maybe we should create an issue for converting VEGAS as well? How difficult do you think it would be? In comparison to the other ones I think it has a bunch more framework calls, but it should be possible, I think?

2021-11-19 11:47 UTC, FHof commented on torchquad/tests/integration_test_functions.py
> +            if is_complex:
Yes, all of them support complex numbers, i.e. `anp.array(1+2j, like="tensorflow")` and `anp.array(1+2j, like="jax")` give complex tensors.

2021-11-19 12:04 UTC, FHof commented on torchquad/tests/integration_test_functions.py
> +            # Tensorflow's exponentiation gives float64 values if x are float32
I think it's not related to the global precision. `tf.constant(1.0, dtype=tf.float32) ** tf.constant(2)` gives a float64 tensor only if numpy behaviour is enabled; otherwise it shows an error. Without numpy behaviour the integrators don't work with tensorflow, e.g. because `reshape` is unavailable. I assume tensorflow is generally more strict and requires, for example, explicit casts whereas other backends automatically cast float to complex.

2021-11-19 12:13 UTC, FHof commented on torchquad/tests/vegas_test.py
> +from integration_test_utils import compute_test_errors
I replaced the compute_test_errors function in the vegas tests now. 
I think it wouldn't be difficult to support other backends in VEGAS if I understand what the code does exactly, but it may be difficult to make it execute fast with all backends.

2021-11-19 12:37 UTC, FHof commented on torchquad/tests/boole_test.py
> +def test_integrate_jax():
When I suggested to enable CUDA by default I thought that torchquad explicitly changes the default device to CPU in __init.py__.
https://github.com/FHof/torchquad/blob/9714ba2bc5a5438f89493b6470ff38a0f5d39fae/torchquad/__init__.py#L4-L6

However, by default torch uses the CPU and it initialises CUDA lazily, for example, when a user uses the device parameter in a tensor initialisation:
https://pytorch.org/docs/stable/notes/cuda.html#cuda-semantics
In torchquad CUDA is initialised when `enable_cuda` executes `torch.cuda.current_device()`, and CUDA is used because `set_precision` changes the default device to cuda via the changed default dtype.
Since for a small number of points, torch on CPU can be faster than torch with CUDA, I'm no longer sure if CUDA should be enabled by default.

I don't know what the TORCH_DEVICE environment variable is used for.
#

To skip missing backends here, I used the `pytest.importorskip` function and kept separate functions for each backend.

2021-11-19 14:12 UTC, gomezzz commented on torchquad/tests/boole_test.py
> +def test_integrate_jax():
Well, but the other frameworks also use the GPU by default, right? I would mostly aim to be consistent here. The fact that it is faster to use CPU for some operations will also be true for other frameworks..

`TORCH_DEVICE`  was used to internally track which one had been selected. It may be obsolete by now

2021-11-19 14:14 UTC, gomezzz approved these changes
Feel free to merge

2021-11-19 16:05 UTC, FHof commented on torchquad/tests/boole_test.py
> +def test_integrate_jax():
Ok, I can open another Pull Request to enable CUDA by default. `__init__.py` is not executed by the test imports, so the `set_log_level` and `enable_cuda` are still required there.

2021-11-19 16:05 UTC, merged