Add a jit_integrate method to NewtonCotes and MonteCarlo
FHof/torchquad pull request #21
Opened 2021-12-18 10:29 UTC by FHof

The method JIT-compiles the evaluation point calculation and final integral calculation but not the integrand evaluation. This can be helpful in situations where it is impossible to compile integrand.

2021-12-21 09:17 UTC, gomezzz requested changes

2021-12-21 09:17 UTC, gomezzz commented on torchquad/integration/monte_carlo.py
> +        if backend in ["tensorflow", "jax"]:
this is starting look like the opposite of what we want (autoray handling the backend stuff for us). 

I presume there is no other way? If so, it would be good if you could write a comment here why it is not done with autoray and what would need to change to do it with autoray.

Further, for this particular feature it would be great if you could add a quick example to the docs as it is no super intuitive how to use this feature and what impact it will have on runtime. (I am not sure if `jit_integrate` is the best name, maybe it could be a little more descriptive?

2021-12-21 09:17 UTC, gomezzz commented on torchquad/integration/newton_cotes.py
> +                    import tensorflow as tf
just out of curiosity: is there any potential problem importing the modules directly and not using them via autoray? E.g. could it happen that autoray uses a different tensorflow install or that the reimport ends up using different devices, settings, etc.? 
I hope not, just wondering if you read anything if this may or may not be a problem?

2021-12-21 16:07 UTC, FHof commented on torchquad/integration/newton_cotes.py
> +                    import tensorflow as tf
I think there's no problem. autoray also imports modules in this way at some places in the code; here's an example: https://github.com/jcmgray/autoray/blob/35677037863d7d0d25ff025998d9fda75dce3b44/autoray/compiler.py#L189
At another place it uses `importlib.import_module`, which, as far as I know, caches the imports of modules like the `import` statement
https://github.com/jcmgray/autoray/blob/35677037863d7d0d25ff025998d9fda75dce3b44/autoray/autoray.py#L200

2021-12-21 16:53 UTC, FHof commented on torchquad/integration/monte_carlo.py
> +        if backend in ["tensorflow", "jax"]:
https://github.com/jcmgray/autoray/blob/35677037863d7d0d25ff025998d9fda75dce3b44/autoray/compiler.py
autoray has an autojit function but it's not included in the released version 0.2.5, it uses the deprecated `experimental_compile` argument with Tensorflow, and the way jit compilation happens differs between backends; for example, PyTorch requires a function with only positional arguments and Tensorflow has the `jit_compile=True` argument to toggle XLA.

2022-01-03 08:29 UTC, gomezzz approved these changes
👍

2022-01-03 12:37 UTC, merged