VEGAS+: Numpy support and more tests
FHof/torchquad pull request #23
Opened 2022-01-11 12:55 UTC by FHof

Summary of changes:
* Numpy support for VEGAS
  * Replace torch. with autoray.numpy. operations
    After this commit it still only works with torch and should indirectly perform the same torch operations as before. I put these changes in an separate commit so that if a regression was introduced later it is easier to find the bug.
  * Replace some numerical operations so that VEGAS+ works with both torch and numpy
  * Add dtype arguments so that it is possible to integrate with float32 precision with numpy
  * A bugfix in the numerical operation replacements where I accidentally used floating point numbers for index calculations
* A new VEGASMap._smooth_map method
* A small docstring fix in VEGAS.integrate
* More tests
  * Support other backends in vegas_test.py and use it to test with Numpy
  * Add special peak test functions to vegas_test.py to check that VEGAS+ works better than MonteCarlo
  * Tests for VEGASMap and VEGASStratification

Relevant issue: #14

2022-01-13 17:09 UTC, gomezzz requested changes
A few minor comments / questions, overall looking good 👍

2022-01-13 17:09 UTC, gomezzz commented on torchquad/integration/vegas_map.py
> +            indices = [0] * (self.N_intervals - 1)
This is the thing that you mentioned where it is more efficient to stay with python datatypes, I think, right? Please add a comment here and below where you then use anp to explain this

2022-01-13 17:09 UTC, gomezzz commented on torchquad/integration/vegas_stratification.py
> +        self.N_strat = int((N_increment / 2.0) ** (1.0 / dim))
I think you wanted to change this to 4, right?

2022-01-14 11:51 UTC, FHof commented on torchquad/integration/vegas_map.py
> +            integration_domain (backend tensor): Integration domain.
I think the docstring was already wrong before my changes. There is no default value in the code, so I removed it from the docstring.
https://github.com/esa/torchquad/blob/d1e532e8986e5ded5ee7f371ad0071c5db1c2663/torchquad/integration/vegas_map.py#L10

2022-01-14 11:56 UTC, FHof commented on torchquad/integration/vegas_map.py
> +                weights[:, i_tmp : i_tmp + 1] + 7.0 * weights[:, i_tmp + 1 : i_tmp + 2],
Yes, the tensors need to have the same shape except on axis 1 so that they can be concatenated.

2022-01-14 12:34 UTC, FHof commented on torchquad/integration/vegas_map.py
> +        ) = self._smooth_map(self.weights, self.counts, self.alpha)
I haven't investigated this. 
In comparison to PyTorch and Numpy, Tensorflow and especially JAX do not support item assignment (see for example https://jax.readthedocs.io/en/latest/jax.ops.html), so I think JAX and Tensorflow don't support re-using existing memory unless the functions are compiled.

2022-01-14 12:55 UTC, FHof commented on torchquad/integration/vegas_stratification.py
> +        self.N_strat = int((N_increment / 2.0) ** (1.0 / dim))
Yes, I haven't added the changes to this PR yet.
I think in VegasFlow they calculate `int(N_increment / 2) / 2`, which approximately corresponds to division by 4,
and in the original implementation it's `(1 - neval_frac) * self.neval / 2.`, where neval_frac is some number between 0 and 1.
https://github.com/N3PDF/vegasflow/blob/21209c928d07c00ae4f789d03b83e518621f174a/src/vegasflow/vflowplus.py#L111-L112
https://github.com/gplepage/vegas/blob/11f67af45c8fc5c8c25060f18a61137274a64789/src/vegas/_vegas.pyx#L1095

2022-01-14 13:51 UTC, FHof commented on torchquad/integration/vegas_stratification.py
> +        self.N_strat = int((N_increment / 2.0) ** (1.0 / dim))
I've added a commit to change it to 4, but the errors in the test are worse now. Previous errors:
```
[0.0, 0.00023080781786584048, 0.0007456416333443405, 0.008323833256319801, 1.5603112756120936, 0.010654779995036279, 9.560055281099267e-05, 1.670036573481193e-05, 0.0005694908455957659]
``` 
Errors with fewer hypercubes:
```
[0.0013054318169358758, 0.0017626261337132091, 0.0009283768196267639, 0.026356434890061564, 4.905033994889436, 0.018269307164842985, 0.0014304650819014775, 2.7983103974504875e-05, 0.0004786292093108546]
```

I think in VegasFlow they calculate `int(N_increment / 2) / 2`, which approximately corresponds to division by 4,
and in the original implementation it's `(1 - neval_frac) * self.neval / 2.`, where neval_frac is some number between 0 and 1.
https://github.com/N3PDF/vegasflow/blob/21209c928d07c00ae4f789d03b83e518621f174a/src/vegasflow/vflowplus.py#L111-L112
https://github.com/gplepage/vegas/blob/11f67af45c8fc5c8c25060f18a61137274a64789/src/vegas/_vegas.pyx#L1095

2022-01-15 11:20 UTC, FHof commented on torchquad/integration/vegas_map.py
> +            indices = [0] * (self.N_intervals - 1)
I added the comments.

2022-01-17 08:48 UTC, gomezzz approved these changes

2022-01-17 13:48 UTC, merged