Mention unsupported backends in the VEGAS docstring and refer to VegasFlow
FHof/torchquad pull request #27
Opened 2022-01-21 15:35 UTC by FHof

2022-01-25 08:15 UTC, gomezzz requested changes

2022-01-25 08:15 UTC, gomezzz commented on torchquad/integration/vegas.py
> +            backend (string, optional): Numerical backend. This argument is ignored if the backend can be inferred from integration_domain. "jax" and "tensorflow" are unsupported. Defaults to "torch"
What happens if you actually pass backend="jax" or TF though? Can you raise an exception in that case? (e.g. NotImplemented )

2022-01-25 11:12 UTC, FHof commented on torchquad/integration/vegas.py
> +            backend (string, optional): Numerical backend. This argument is ignored if the backend can be inferred from integration_domain. "jax" and "tensorflow" are unsupported. Defaults to "torch"
Yes, I've added an exception for this case now. If "jax" or "tensorflow" was passed before, an exception happened when the first unsupported operation was executed.

2022-01-27 09:49 UTC, gomezzz approved these changes

2022-01-27 12:24 UTC, merged