RNG: Add an option to save and restore the state with PyTorch
FHof/torchquad pull request #42
Opened 2022-03-01 16:30 UTC by FHof

With this the user can change the RNG seed in a VEGAS integrand without changing the sample points.
Measurements showed that the uniform function is ca. 4 µs slower with CPU and 30 µs slower with CUDA when the state is saved and restored, so I disabled the option by default.

Alternatively the user can maintain a separate state by modifying the integrand function.

2022-03-02 11:24 UTC, gomezzz requested changes
Minimal change

2022-03-02 11:24 UTC, gomezzz commented on torchquad/integration/utils.py
> +                self.uniform = uniform_func
This might deserves its own local _function I'd say :)

2022-03-03 10:31 UTC, FHof commented on torchquad/integration/utils.py
> +                self.uniform = uniform_func
I've moved it into a method.

2022-03-14 12:25 UTC, gomezzz approved these changes
👍

2022-03-14 15:01 UTC, merged